from helper_func import display_email_campaigns, display_user_personas, display_user_responses, save_as_docx
from agents.email_gen_agent.agent import generate_email_campaigns_for_experiment
from agents.response_evaluator_agent.agent import evaluate_experiment
from agents.response_sim_agent.agent import response_to_email
from agents.persona_gen_agent.agent import generate_personas
from agents.exp_gen_agent.agent import generate_experiments
from product_input import product_description
from dotenv import load_dotenv
import streamlit as st
import time
import os
import io

# Load environment variables from .env file
load_dotenv()

def main():
    """
    Main function that runs the Streamlit application for AI-Driven A/B Testing.
    This application allows users to conduct AI-powered A/B testing by entering
    a product description and API key.
    """
    # App framework setup
    st.title('AI-Driven A/B Testing for Smarter Decision Making')
    st.subheader('Run AI-Powered A/B Testing for Your Product, Just Enter a Description and API Key to Begin!')

    # Input field for selecting sample population size
    num_people = st.number_input("Select the number of people:", min_value=2, max_value=50)

    # Button to confirm sample population
    if st.button("Submit"):
        if num_people and int(num_people):
            st.success("Sample population accepted!")
    else:
        st.error("Please enter a valid ")

    # Input field for API key
    api_key =  st.text_input('Enter Google Generative AI API KEY (Required)')
    st.link_button("Click to get API KEY (select create api key in new project)", "https://makersuite.google.com/app/apikey", type="secondary")

    # Initialize session state variables if they don't exist
    if 'resp_content' not in st.session_state:
        st.session_state.resp_content = None
    if 'gen_email_campaign_a' not in st.session_state:
        st.session_state.gen_email_campaign_a = None
    if 'gen_email_campaign_b' not in st.session_state:
        st.session_state.gen_email_campaign_b = None
    if 'users_personas' not in st.session_state:
        st.session_state.users_personas = None
    if 'all_user_responses' not in st.session_state:
        st.session_state.all_user_responses = None
    if 'experiment_valuation' not in st.session_state:
        st.session_state.experiment_valuation = None

    # Reset button to clear all session state variables
    if st.button("Reset Experiment"):
        st.session_state.resp_content = None
        st.session_state.gen_email_campaign_a = None
        st.session_state.gen_email_campaign_b = None
        st.session_state.users_personas = None
        st.session_state.all_user_responses = None
        st.session_state.experiment_valuation = None

    product_input = st.text_area(label='Please enter product description: ', placeholder=product_description(), height=300)

    if not product_input:
        product_input = product_description()

    api_key = api_key if api_key else os.environ.get('GEMINI_API')

    if st.button("Generate AB test experiment") and api_key and num_people:
        os.environ["GEMINI_API"] = api_key
        
        with st.status(f"AB experiment creation started by AI agent", expanded=True) as status:
            st.write(f"Constructing Prompt")
            time.sleep(2)

            st.write("API call to Gemini AI sent")

            start_time = time.time()
            st.session_state.resp_content = generate_experiments(str(1), product_input)
            end_time = time.time()
            
            ab_elapsed_time = round((end_time - start_time), 2)

            st.write(f"Response recieved in {ab_elapsed_time} seconds !!")
            st.write("Formating Response !!")
            time.sleep(1)
            
            status.update(
                label="Response completed !", state="complete", expanded=False
            )
    
        st.markdown(st.session_state.resp_content.experiment_id)
        st.markdown(st.session_state.resp_content.product_description)
        st.markdown(st.session_state.resp_content.experiment_guidelines)

        if st.session_state.resp_content:
            edited_response = st.text_area("Edit AB test agent response if needed:", value=st.session_state.resp_content.experiment_guidelines)
            st.session_state.resp_content.experiment_guidelines = edited_response

    if st.session_state.resp_content and st.button("Generate AB test email_campaign A and B") and api_key:

        with st.status(f"A and B email being Generated by AI agent", expanded=True) as status:
            st.write(f"Constructing Prompt")
            time.sleep(2)

            st.write("API call to Gemini AI sent")

            start_time = time.time()
            st.session_state.gen_email_campaign_a, st.session_state.gen_email_campaign_b = generate_email_campaigns_for_experiment(st.session_state.resp_content)
            end_time = time.time()
            
            ab_email_elapsed_time = round((end_time - start_time), 2)

            st.write(f"Response recieved in {ab_email_elapsed_time} seconds !!")
            st.write("Formating Response !!")
            time.sleep(1)
            
            status.update(
                label="Response completed !", state="complete", expanded=False
            )

        df_email = display_email_campaigns(st.session_state.gen_email_campaign_a, st.session_state.gen_email_campaign_b)

        if st.session_state.gen_email_campaign_a and st.session_state.gen_email_campaign_b:

            st.session_state.gen_email_campaign_a.variant = st.text_area("Edit campaign A agent response if needed:", value=st.session_state.resp_content.experiment_guidelines)
            st.session_state.gen_email_campaign_a.subject
            st.session_state.gen_email_campaign_a.body
            st.session_state.gen_email_campaign_a.tone
            st.session_state.gen_email_campaign_a.target_audience


            st.session_state.gen_email_campaign_b.variant = st.text_area("Edit campaign B agent response if needed:", value=st.session_state.resp_content.experiment_guidelines)
            st.session_state.gen_email_campaign_b.subject
            st.session_state.gen_email_campaign_b.body
            st.session_state.gen_email_campaign_b.tone
            st.session_state.gen_email_campaign_b.target_audience

        # Display email table in Streamlit
        st.subheader("AB Test Email Campaigns")
        st.dataframe(df_email)

        st.download_button(
            label="Download email as CSV",
            data=df_email.to_csv().encode("utf-8"),
            file_name='email_campaigns_df.csv',
            mime='text/csv',
            icon=":material/download:",
        )

    if st.session_state.gen_email_campaign_a and st.session_state.gen_email_campaign_b and st.button("Generate AB test Users Personas") and num_people:

        with st.status(f"User Personas being Generated by AI agent", expanded=True) as status:
            st.write(f"Constructing Prompt")
            time.sleep(2)

            st.write("API call to Gemini AI sent")

            start_time = time.time()
            st.session_state.users_personas = generate_personas(st.session_state.gen_email_campaign_a.target_audience, st.session_state.gen_email_campaign_b.target_audience, num_people)
            end_time = time.time()
            
            user_persona_elapsed_time = round((end_time - start_time), 2)

            st.write(f"Response recieved in {user_persona_elapsed_time} seconds !!")
            st.write("Formating Response !!")
            time.sleep(1)
            
            status.update(
                label="Response completed !", state="complete", expanded=False
            )

        df_user_persona = display_user_personas(st.session_state.users_personas)

        # Display Persona table in Streamlit
        st.subheader("AB Test User Personas")
        st.dataframe(df_user_persona)

        st.download_button(
            label="Download user personas as CSV",
            data=df_user_persona.to_csv().encode("utf-8"),
            file_name='user_persona_df.csv',
            mime='text/csv',
            icon=":material/download:",
        )

    if st.session_state.users_personas and st.button("Generate AB test Users Responses") and api_key:

        selected_campaigns = {'A':st.session_state.gen_email_campaign_a, 'B':st.session_state.gen_email_campaign_b}

        with st.status(f"AI agents getting Persona responses on emails", expanded=True) as status:
            st.write(f"Constructing Prompt")
            time.sleep(2)

            st.write("Gathering responses from persona")

            all_user_responses = []
            total_time_elapsed = 0

            for i, user in enumerate(st.session_state.users_personas.personas):

                start_time = time.time()
                user_resp, _ = response_to_email(user, selected_campaigns)
                end_time = time.time()

                all_user_responses.append(user_resp)

                persona_resp_elapsed_time = round((end_time - start_time), 2)

                st.write(f"Response recieved for persona {i+1} in {persona_resp_elapsed_time} seconds !!")
                total_time_elapsed += persona_resp_elapsed_time

                time.sleep(12)
            
            st.write(f"Total time elapsed collecting response: {total_time_elapsed}")
            
            st.write("Formating Response !!")
            time.sleep(1)
            
            status.update(
                label="Response completed !", state="complete", expanded=False
            )

        st.session_state.all_user_responses = all_user_responses

        df_user_responses = display_user_responses(st.session_state.all_user_responses)

        # Display Response table in Streamlit
        st.subheader("AB Test User Responses")
        st.dataframe(df_user_responses)

        st.download_button(
            label="Download persona response data as CSV",
            data=df_user_responses.to_csv().encode("utf-8"),
            file_name='user_response_df.csv',
            mime='text/csv',
            icon=":material/download:",
        )
    
    if st.session_state.all_user_responses and st.button("Generate AB test Result Report") and api_key:

        st.session_state.experiment_valuation = evaluate_experiment(product_input, st.session_state.resp_content, st.session_state.gen_email_campaign_a, st.session_state.gen_email_campaign_b, st.session_state.users_personas, st.session_state.all_user_responses)

        # Display Response of Experiment
        st.subheader("AB Test Experiment Report")
        st.markdown(st.session_state.experiment_valuation.Introduction)
        st.markdown(st.session_state.experiment_valuation.Experiment_process)
        st.markdown(st.session_state.experiment_valuation.Email_Campaign_Analysis)
        st.markdown(st.session_state.experiment_valuation.User_Persona_Analysis)
        st.markdown(st.session_state.experiment_valuation.User_Response_Analysis)
        st.markdown(st.session_state.experiment_valuation.Performance_Metrics)
        st.markdown(st.session_state.experiment_valuation.Interpretations)
        st.markdown(st.session_state.experiment_valuation.Recommendations)
        st.markdown(st.session_state.experiment_valuation.Conclusion)
    
    if st.session_state.experiment_valuation and st.button("Save AB test Result Report") and api_key:

        doc_file = save_as_docx(st.session_state.experiment_valuation, "AB_Test_Report.docx", isWF=False)

        bio = io.BytesIO()
        doc_file.save(bio)

        st.download_button(
            label="Click here to download",
            data=bio.getvalue(),
            file_name="AB_Test_Report.docx",
            mime="docx"
        )

    st.write("Made with ❤️ by Amogh Mahadev kokari ©️ 2025 _||_ [linkedin](https://www.linkedin.com/in/amoghkokari/) _||_ [Portfolio](https://amoghkokari.github.io/portfolio.pdf) _||_ [Github](https://github.com/amoghkokari)")

if __name__ == "__main__":
    main()
